### ISSUE TITLE
The dn key-value pair is not URI.decode'd

### ISSUE THREAD

**Issue by seaforium** [rustra/magnet#1]
The code that implements Collectable protocol for the Magnet struct does not call `URI.decode` on the `name` key (marked as `dn` in magnet links.)

As a result the name has `%20` in it instead of spaces. Also, if we run `Magnet.encode` on the struct with such a name, we will get `%2520` in our magnet link instead of just `%20`.

**Comment by gausby** [comment]
Feel free to open a pull request.

**Comment by seaforium** [comment]
I am quite new to git and Github so it will take me some time to learn the ropes, but I'll try!

**Comment by gausby** [comment]
I can see that you forked the project, so you are well on your way. If you need to know about Git there is a free book on the topic called [Pro Git](https://git-scm.com/book/en/v2).

In short, when you got the code locally (using the `git clone` command as described on the github page for your fork) you can make the changes to the code; use `git add` to add the files to the "staging area", and finally use the `git commit` command to accept the changes into a commit. When you push the changes to github (using `git push`) you will be offered a chance to make the changes into a pull request—at which point I can review it and give you feedback/accept the changes.

Don't be afraid to ask if you have any questions :)

**Comment by seaforium** [comment]
Thank you for all the help! I appreciate it :)

I'll definitely check the book out to solidify my knowledge as it's pretty fragmented at the moment.

**Comment by rustra** [comment]
@seaforium I'm closing this issue because it's fixed by https://github.com/rustra/magnet/pull/6.
