### ISSUE TITLE
The xt key-value pair is URI.encode'd

### ISSUE THREAD

**Issue by seaforium** [rustra/magnet#2]
`Magnet.encode` call `URI.encode` on `info_hash` key (marked `xt` in magnet links).

This turns `urn:btih:` part into `urn%3Abtih%3A` and thus makes a magnet link invalid.

**Comment by gausby** [comment]
Feel free to open a pull request on this one.

**Comment by rustra** [comment]
@seaforium I'm closing this issue because it's fixed by https://github.com/rustra/magnet/pull/6.
