### ISSUE TITLE
Magnet.Encoder leaves numbers in tr keys

### ISSUE THREAD

**Issue by seaforium** [rustra/magnet#3]
The magnet link we get from `Magnet.encode` has parts that looks like `tr.1=`, `tr.2=` while it should be just `tr` in each instance.

My understanding is that you add numbers because you collect everything in a map which requires the keys to be unique, and then feed it to `URI.encode_query`. I wonder whether it would be better do collect everything in a keyword list instead since the documentation says that the function:

> Takes an enumerable that enumerates as a list of two-element tuples (e.g., a
map or **a keyword list**) and returns a string in the form of
key1=value1&key2=value2... where keys and values are URL encoded as per
encode_www_form/1.

**Comment by gausby** [comment]
You might be right that the `.n` suffix on the `tr` field is not needed. It is kinda hard to know because the specification is rather vague. [BEP0009](http://bittorrent.org/beps/bep_0009.html) says:

> `tr` is a tracker url, if there is one. If there are multiple trackers, multiple tr entries may be included. The same applies for `x.pe` entries.

I add them because them because other sources, such as the [wikipedia](https://en.wikipedia.org/wiki/Magnet_URI_scheme) article specifies that

> The standard also allows for multiple parameters of the same type to be used by appending ".1", ".2", etc. to the parameter name…

The *wikipedia_en_all_novid_2018-06.zim*-example on the same wikipedia entry has multiple `tr` fields without the dot-n-numberings scheme, so I guess they are allowed. Feel free to open a pull request.

**Comment by seaforium** [comment]
In #4 I mentioned that I tried giving magnet links to Transmission; it successfully parsed keys like `tr.1` so I am not sure about this issue anymore. The way you do it might not be necessary but it seems that it isn't incorrect either.

I wonder what if there were another function, something like `Magnet.normalize`, in addition to `encode` and `decode` that would order the keys and remove numbers? Its purpose would not be to implement BEP0009 as you already did it and did it correctly, it seems, but rather make sure that torrent clients that *interpret* BEP differently can understand magnet links produced by the package.

**Comment by gausby** [comment]
I think it should be an option passed to the encode-function; this can happen by upgrading the `encode/1` function to an arity 2-function; `encode/2` will take the data to encode as its first argument and a keyword list as its second argument. To maintain backwards compatibility the `encode/1` version can call the `encode/2` variant with the default options set.

```elixir
def encode(data) do
  encode(data, [])
end

def encode(data, opts) do
  # … actual encoding of `data`
end
```

I think it is easier to grasp such an interface, as calling `encode/1` should just do "the right thing", and no fix ups on the resulting data is needed…and documenting a list of options is easier than documenting a series of functions to call in the correct order.

I hope that makes sense.

**Comment by seaforium** [comment]
Thank you for the explanation. It does make sense and looks like a much better solution to me.

**Comment by rustra** [comment]
@seaforium I'm closing this issue because it's fixed by https://github.com/rustra/magnet/pull/6.
